### ISSUE TITLE
Exception with empty files

### ISSUE THREAD

**Issue by HackbrettXXX** [sleiphur/CodeMiniMap#1]
First of all thanks for this awesome plugin. It works great most of the time. However, if I create a new TypeScript file (which is immediately opened) I get an exception: 
```
Worker exited due to exception

java.lang.IndexOutOfBoundsException: Wrong line: 0. Available lines count: 0
	at com.intellij.openapi.editor.impl.LineSet.checkLineIndex(LineSet.java:198)
	at com.intellij.openapi.editor.impl.LineSet.getLineStart(LineSet.java:179)
	at com.intellij.openapi.editor.impl.LineIteratorImpl.getStart(LineIteratorImpl.java:35)
	at xyz.sleipnir.codeminimap.renderer.CodeMiniMap.update(CodeMiniMap.kt:95)
	at xyz.sleipnir.codeminimap.comps.CodeMiniMapPanel$9.computeInReadAction(CodeMiniMapPanel.kt:156)
	at com.intellij.openapi.progress.util.ReadTask.performInReadAction(ReadTask.java:49)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:869)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:260)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:56)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:56)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:258)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$100(ProgressIndicatorUtils.java:45)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:208)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

The plugin keeps working after the exception occurs, but the "IDE Fatal Errors" button in the status bar starts blinking red and reports this exception from the plugin.

I'm running:
```
WebStorm 2020.2.3
Build #WS-202.7660.23, built on September 30, 2020

Runtime version: 11.0.8+10-b944.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 6916M
Cores: 12
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: Code MiniMap, com.intellij.apacheConfig, org.antlr.intellij.plugin, com.intellij.lang.jsgraphql, org.asciidoctor.intellij.asciidoc
```

Let me know if you need further details.

**Comment by sleiphur** [comment]
[https://github.com/sleiphur/CodeMiniMap/releases/tag/1.6.5](url)
